apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- virtual-service.yaml
namespace: production
images:
- name: kowlon/go-echo
  newName: 490004610217.dkr.ecr.ap-southeast-1.amazonaws.com/go-ecommerce-product
  newTag: latest
patches:
- path: env-patch.yaml
  target:
    kind: Deployment
    name: ecommerce-product
    namespace: production
